In [ ]:
#Python collection datatypes 
    #Lists
    #Tuples
    #Sets 
    #Dictionaries
#Numpy package - Mathematical calculations & Arrays and Matries 
    #Array
    #Matrices 

In [1]:
myfirstlist = [1,2,3,4,5,6,7,8,9,10]

In [2]:
type(myfirstlist)

list

In [3]:
myfirstlist[5]

6

In [4]:
myfirstlist[0:3]

[1, 2, 3]

In [5]:
myfirstlist[4:]

[5, 6, 7, 8, 9, 10]

In [6]:
myfirstlist[:5]

[1, 2, 3, 4, 5]

In [7]:
myfirstlist[-1]

10

In [8]:
myfirstlist[-4:]

[7, 8, 9, 10]

In [9]:
myfirstlist.append(20)

In [12]:
myfirstlist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20]

In [13]:
myfirstlist.insert(5,11)

In [14]:
myfirstlist

[1, 2, 3, 4, 5, 11, 6, 7, 8, 9, 10, 20]

In [16]:
myfirstlist1 = myfirstlist.copy()

In [18]:
myfirstlist1.remove(11)

In [20]:
myfirstlist1.pop(10)

20

In [22]:
myfirstlist1.append(4)

In [24]:
myfirstlist1.sort()

In [26]:
myfirstlist1.reverse()

In [27]:
myfirstlist1

[10, 9, 8, 7, 6, 5, 4, 4, 3, 2, 1]

In [29]:
myfirstlist1.clear()

In [31]:
myfirstlist1

[]

In [32]:
del myfirstlist1

In [33]:
len(myfirstlist1)

NameError: name 'myfirstlist1' is not defined

In [34]:
myfirstlist1 = ['a','b','c',1,2,3]

In [35]:
myfirstlist1

['a', 'b', 'c', 1, 2, 3]

In [36]:
myfirstlist1[0] = 'z'

In [38]:
type(myfirstlist1)

list

In [52]:
myfirsttuple = (1,2,3,4,5,5,5,5,5,5,6,7,8,9,10,11)

In [40]:
type(myfirsttuple)

tuple

In [42]:
myfirsttuple[0]=100

TypeError: 'tuple' object does not support item assignment

In [53]:
myfirsttuple.index(11)

15

In [46]:
myfirsttuple.count(5)

6

In [47]:
len(myfirsttuple)

15

In [49]:
del myfirsttuple

In [55]:
sales = [23435, 44545, 55656, 66566]
profit = [3345,4454,3455,6665]

In [ ]:
profitratio = profit/sales

In [56]:
profitratio = []
for i in range(0, len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

[0.14273522509067635,
 0.0999887753956673,
 0.062077763403765994,
 0.10012619054772706]

In [60]:
myfirstdict = {"Customer Name": 'Rahul', 'order id': 123, 'Segment': 'Python'}
#How to change the key name - Mayank

In [62]:
myfirstdict["Segment"] = 'Tableau'

In [64]:
myfirstdict['Region'] = 'North'

In [66]:
len(myfirstdict)

4

In [67]:
myfirstdict.pop('Customer Name')

'Rahul'

In [69]:
myfirstdict.clear()

In [70]:
myfirstdict

{}

In [71]:
del myfirstdict

In [72]:
myfirstset = {1,2,2,3,3,4,4,4,5,6,7,8}

In [73]:
myfirstset

{1, 2, 3, 4, 5, 6, 7, 8}

In [74]:
myfirstset[5]=100

TypeError: 'set' object does not support item assignment

In [75]:
myfirstset[0]

TypeError: 'set' object does not support indexing

In [76]:
len(myfirstset)

8

In [77]:
myfirstset.remove(5)

In [79]:
myfirstset.add(20)

In [80]:
myfirstset

{1, 2, 3, 4, 6, 7, 8, 20}

In [81]:
myfirstset.update([12,23,34,45,56])

In [82]:
myfirstset

{1, 2, 3, 4, 6, 7, 8, 12, 20, 23, 34, 45, 56}

In [83]:
myfirstset.remove(5)

KeyError: 5

In [114]:
myfirstset.discard(6)

In [115]:
myfirstset

{1, 2, 3, 4, 7, 8, 12, 20, 23, 34, 45, 56}

In [117]:
myfirstset

{2, 3, 4, 7, 8, 12, 20, 23, 34, 45, 56}

In [116]:
myfirstset.pop()

1

In [118]:
myfirstset.clear()

In [120]:
del myfirstset

In [ ]:
myfirstlist.

In [121]:
mylist = [1,2,43]

In [122]:
mylist1 = [2,3,4]

In [123]:
mylist1.extend(mylist)

In [124]:
mylist1

[2, 3, 4, 1, 2, 43]

In [125]:
import numpy as np

In [126]:
sales

[23435, 44545, 55656, 66566]

In [127]:
profit

[3345, 4454, 3455, 6665]

In [128]:
sales_array = np.array(sales)

In [129]:
profit_array = np.array(profit)

In [132]:
sales_array

array([23435, 44545, 55656, 66566])

In [133]:
profit_array

array([3345, 4454, 3455, 6665])

In [134]:
profit_array/sales_array

array([0.14273523, 0.09998878, 0.06207776, 0.10012619])

In [ ]:
!pip install packagename

In [135]:
sales

[23435, 44545, 55656, 66566]

In [136]:
sales_array

array([23435, 44545, 55656, 66566])

In [137]:
sales*3

[23435,
 44545,
 55656,
 66566,
 23435,
 44545,
 55656,
 66566,
 23435,
 44545,
 55656,
 66566]

In [138]:
sales_array*3

array([ 70305, 133635, 166968, 199698])

In [139]:
list1 = [2,3,4,5,6,7,8]

In [141]:
array1= np.array(list1)

In [143]:
array1[0]=10

In [146]:
array2 = array1.copy()

In [157]:
array2[0]=10

In [153]:
array1

array([10,  3,  4,  5,  6,  7,  8])

In [151]:
array3 = array1[0:5]

In [154]:
array3[0]=5

In [159]:
array3

array([5, 3, 4, 5, 6])

In [160]:
array1

array([5, 3, 4, 5, 6, 7, 8])

In [158]:
array2

array([10,  3,  4,  5,  6,  7,  8])

In [164]:
list1 = [1,2,3,4,5,'R']

In [165]:
list1

[1, 2, 3, 4, 5, 'R']

In [163]:
np.array(list1)

array(['1', '2', '3', '4', '5', 'R'], dtype='<U11')

In [166]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [169]:
list1 = [True, False, False, True, 'True']

In [170]:
np.array(list1)

array(['True', 'False', 'False', 'True', 'True'], dtype='<U5')

In [182]:
list1 = np.arange(0,20)

In [183]:
list1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [185]:
type(np.reshape(list1, (5,4), 'F'))

numpy.ndarray

In [186]:
tupe1 = (0,1,2,3,4,5,6,7,8,9)

In [190]:
np.reshape(tupe1, (5,2), 'F').T

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [191]:
sales_us = [1234,2345,3456]
sales_eu = [2345,1234,3333]
sales_jp = [3456,3333,2323]

In [194]:
sales_mat = np.array([sales_eu,sales_us,sales_jp])

In [195]:
profit_us = [123,324,333]
profit_eu = [333,434,333]
profit_jp = [333,434,333]

In [196]:
profit_mat = np.array([profit_eu,profit_us,profit_jp])

In [197]:
profit_mat

array([[333, 434, 333],
       [123, 324, 333],
       [333, 434, 333]])

In [198]:
profit_mat/sales_mat

array([[0.14200426, 0.35170178, 0.09990999],
       [0.09967585, 0.13816631, 0.09635417],
       [0.09635417, 0.13021302, 0.14334912]])

In [200]:
sales_mat[2,1]

3333

In [201]:
sales_mat

array([[2345, 1234, 3333],
       [1234, 2345, 3456],
       [3456, 3333, 2323]])